Document: mysql-sandbox
Title: Debian mysql-sandbox Manual
Author: <insert document author here>
Abstract: This manual describes what mysql-sandbox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mysql-sandbox/mysql-sandbox.sgml.gz

Format: postscript
Files: /usr/share/doc/mysql-sandbox/mysql-sandbox.ps.gz

Format: text
Files: /usr/share/doc/mysql-sandbox/mysql-sandbox.text.gz

Format: HTML
Index: /usr/share/doc/mysql-sandbox/html/index.html
Files: /usr/share/doc/mysql-sandbox/html/*.html
